# Generated by Django 5.2.9 on 2025-12-17 01:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlindsTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('is_global', models.BooleanField(default=False, verbose_name='Is Global')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blinds_templates', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Blinds Template',
                'verbose_name_plural': 'Blinds Templates',
            },
        ),
        migrations.CreateModel(
            name='BlindsLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('level_number', models.PositiveIntegerField(verbose_name='Level Number')),
                ('small_blind', models.PositiveIntegerField(verbose_name='Small Blind')),
                ('big_blind', models.PositiveIntegerField(verbose_name='Big Blind')),
                ('duration_minutes', models.PositiveIntegerField(verbose_name='Duration (Minutes)')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='levels', to='blinds.blindstemplate', verbose_name='Blinds Template')),
            ],
            options={
                'verbose_name': 'Blinds Level',
                'verbose_name_plural': 'Blinds Levels',
                'ordering': ['level_number'],
            },
        ),
    ]
