# Generated by Django 5.2.9 on 2025-12-26 13:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlindsSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('is_global', models.BooleanField(default=False, verbose_name='Is Global')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blinds_schedules', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
            ],
            options={
                'verbose_name': 'Blinds Schedule',
                'verbose_name_plural': 'Blinds Schedules',
            },
        ),
        migrations.CreateModel(
            name='BlindsScheduleLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('level_index', models.PositiveIntegerField()),
                ('level_type', models.CharField(choices=[('play', 'Play'), ('break', 'Break')], max_length=10)),
                ('duration_seconds', models.PositiveIntegerField()),
                ('small_blind', models.PositiveIntegerField(blank=True, null=True)),
                ('big_blind', models.PositiveIntegerField(blank=True, null=True)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='levels', to='timers.blindsschedule', verbose_name='Blinds Schedule')),
            ],
            options={
                'verbose_name': 'Blinds Schedule Level',
                'verbose_name_plural': 'Blinds Schedule Levels',
            },
        ),
        migrations.CreateModel(
            name='BlindsTimer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_finished', models.BooleanField(auto_created=True, default=False)),
                ('accumulated_pause_seconds', models.PositiveIntegerField(auto_created=True, default=0)),
                ('paused_at', models.DateTimeField(auto_created=True, blank=True, null=True)),
                ('is_paused', models.BooleanField(auto_created=True, default=False)),
                ('level_started_at', models.DateTimeField(auto_created=True, blank=True, null=True)),
                ('current_level_index', models.PositiveIntegerField(auto_created=True, default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='timers', to='events.event')),
            ],
            options={
                'verbose_name': 'Blinds Timer',
                'verbose_name_plural': 'Blinds Timers',
            },
        ),
        migrations.CreateModel(
            name='BlindsTimerLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('level_index', models.PositiveIntegerField()),
                ('level_type', models.CharField(choices=[('play', 'Play'), ('break', 'Break')], max_length=10)),
                ('duration_seconds', models.PositiveIntegerField()),
                ('small_blind', models.PositiveIntegerField(blank=True, null=True)),
                ('big_blind', models.PositiveIntegerField(blank=True, null=True)),
                ('timer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='levels', to='timers.blindstimer', verbose_name='Blinds Timer')),
            ],
            options={
                'verbose_name': 'Blinds Timer Level',
                'verbose_name_plural': 'Blinds Timer Levels',
            },
        ),
    ]
