# Generated by Django 5.2.9 on 2025-12-21 08:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0003_alter_participant_final_position_guestparticipant'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlindsTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('is_global', models.BooleanField(default=False, verbose_name='Is Global')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blinds_templates', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Blinds Template',
                'verbose_name_plural': 'Blinds Templates',
            },
        ),
        migrations.CreateModel(
            name='BlindsLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('level_index', models.PositiveIntegerField()),
                ('level_type', models.CharField(choices=[('play', 'Play'), ('break', 'Break')], max_length=10)),
                ('duration_seconds', models.PositiveIntegerField()),
                ('small_blind', models.PositiveIntegerField(blank=True, null=True)),
                ('big_blind', models.PositiveIntegerField(blank=True, null=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='levels', to='timers.blindstemplate', verbose_name='Blinds Template')),
            ],
            options={
                'ordering': ['level_index'],
            },
        ),
        migrations.CreateModel(
            name='BlindsTimer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('current_level_index', models.PositiveIntegerField(default=0)),
                ('level_started_at', models.DateTimeField(blank=True, null=True)),
                ('is_paused', models.BooleanField(default=False)),
                ('paused_at', models.DateTimeField(blank=True, null=True)),
                ('accumulated_pause_seconds', models.PositiveIntegerField(default=0)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timers', to='events.event')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='timers', to='timers.blindstemplate')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
