# Generated by Django 5.2.9 on 2026-01-24 03:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlindsTimer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_level_index', models.PositiveIntegerField(auto_created=True, default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('current_level_started_at', models.DateTimeField(auto_now_add=True)),
                ('state', models.CharField(choices=[('running', 'Running'), ('paused', 'Paused'), ('finished', 'Finished')], default='running', max_length=50)),
                ('accumulated_pause_seconds', models.FloatField(default=0.0)),
                ('paused_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='timers', to='events.event')),
            ],
            options={
                'verbose_name': 'Blinds Timer',
                'verbose_name_plural': 'Blinds Timers',
            },
        ),
        migrations.CreateModel(
            name='BlindsTimerLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('level_index', models.PositiveIntegerField()),
                ('level_type', models.CharField(choices=[('play', 'Play'), ('break', 'Break')], max_length=10)),
                ('duration_seconds', models.PositiveIntegerField()),
                ('small_blind', models.PositiveIntegerField(blank=True, null=True)),
                ('big_blind', models.PositiveIntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('management_messages', models.JSONField(blank=True, default=dict)),
                ('timer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='levels', to='timers.blindstimer', verbose_name='Blinds Timer')),
            ],
            options={
                'verbose_name': 'Blinds Timer Level',
                'verbose_name_plural': 'Blinds Timer Levels',
            },
        ),
    ]
