# Generated by Django 5.2.9 on 2026-01-24 07:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blindstimer',
            old_name='accumulated_pause_seconds',
            new_name='skipped_ms',
        ),
        migrations.AlterField(
            model_name='blindstimer',
            name='current_level_started_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='blindstimer',
            name='paused_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='blindstimerlevel',
            name='level_type',
            field=models.CharField(choices=[('play', 'Play'), ('break', 'Break')], default='play', max_length=10),
        ),
    ]
