# Generated by Django 5.2.9 on 2025-12-27 19:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blindstimer',
            name='current_level_index',
        ),
        migrations.AddField(
            model_name='blindstimer',
            name='start_level_index',
            field=models.PositiveIntegerField(auto_created=True, default=1),
        ),
        migrations.AlterField(
            model_name='blindstimer',
            name='is_paused',
            field=models.BooleanField(auto_created=True, default=True),
        ),
        migrations.AlterField(
            model_name='blindstimer',
            name='level_started_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blindstimer',
            name='paused_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
