# Generated by Django 5.2.9 on 2025-12-21 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blindslevel',
            options={'ordering': ['level_index'], 'verbose_name': 'Blinds Level', 'verbose_name_plural': 'Blinds Levels'},
        ),
        migrations.AlterModelOptions(
            name='blindstimer',
            options={'verbose_name': 'Blinds Timer', 'verbose_name_plural': 'Blinds Timers'},
        ),
    ]
