# Generated by Django 5.2.9 on 2025-12-22 09:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0004_memberstatistics_and_more'),
        ('events', '0007_remove_eventrsvp_rsvp_user_or_guest_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PointsLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('points_delta', models.IntegerField()),
                ('reason', models.CharField(max_length=255)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='points_ledger', to='events.event')),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points_ledger', to='common.seasonmembership')),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('membership', 'event'), name='unique_points_per_event')],
            },
        ),
    ]
