# Generated by Django 5.2.9 on 2025-12-26 02:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('name', models.CharField(max_length=255, verbose_name='Season Name')),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='End Date')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('is_active',), name='unique_active_season')],
            },
        ),
        migrations.CreateModel(
            name='SeasonMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('points', models.IntegerField(default=0, verbose_name='Points')),
                ('rebuys', models.PositiveIntegerField(default=0, verbose_name='Rebuys')),
                ('special_data', models.JSONField(blank=True, default=dict, verbose_name='Special Data')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='common.season', verbose_name='Season')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='season_memberships', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'unique_together': {('user', 'season')},
            },
        ),
        migrations.CreateModel(
            name='MemberStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('membership', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to='common.seasonmembership')),
            ],
            options={
                'verbose_name': 'Member Statistics',
                'verbose_name_plural': 'Member Statistics',
            },
        ),
    ]
