# Generated by Django 5.2.9 on 2025-12-21 02:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('name', models.CharField(max_length=255, verbose_name='Season Name')),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='End Date')),
                ('active', models.BooleanField(default=True, verbose_name='Is Active')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SeasonMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('points', models.IntegerField(default=0, verbose_name='Points')),
                ('rebuys', models.PositiveIntegerField(default=0, verbose_name='Rebuys')),
                ('rebuys_stolen', models.PositiveIntegerField(default=0, verbose_name='Rebuys Stolen')),
                ('special_data', models.JSONField(blank=True, default=dict, verbose_name='Special Data')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='common.season', verbose_name='Season')),
            ],
        ),
    ]
