# Generated by Django 5.2.9 on 2025-12-21 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='season',
            old_name='active',
            new_name='is_active',
        ),
    ]
