# Generated by Django 5.2.9 on 2025-12-21 22:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_rename_active_season_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Member Statistics',
                'verbose_name_plural': 'Member Statistics',
            },
        ),
        migrations.RemoveField(
            model_name='seasonmembership',
            name='rebuys_stolen',
        ),
        migrations.AddConstraint(
            model_name='season',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('is_active',), name='unique_active_season'),
        ),
        migrations.AddField(
            model_name='memberstatistics',
            name='membership',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to='common.seasonmembership'),
        ),
    ]
