# Generated by Django 5.2.9 on 2025-12-21 02:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='eventrsvp',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rsvps', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='participant',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='events.event', verbose_name='Event'),
        ),
        migrations.AddField(
            model_name='participant',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddConstraint(
            model_name='eventrsvp',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('guest_name', ''), ('user__isnull', False)), models.Q(('guest_name__gt', ''), ('user__isnull', True)), _connector='OR'), name='rsvp_user_or_guest'),
        ),
        migrations.AddConstraint(
            model_name='eventrsvp',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('user', 'event'), name='unique_user_rsvp'),
        ),
        migrations.AddConstraint(
            model_name='eventrsvp',
            constraint=models.UniqueConstraint(condition=models.Q(('guest_email__gt', '')), fields=('guest_email', 'event'), name='unique_guest_rsvp'),
        ),
    ]
