# Generated by Django 5.2.9 on 2025-12-17 01:07

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokerevent',
            name='end_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, verbose_name='End Date'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='PokerEventRSVP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('guest_name', models.CharField(blank=True, max_length=100)),
                ('guest_email', models.EmailField(blank=True, max_length=254)),
                ('status', models.CharField(choices=[('going', 'Going'), ('late', 'Late'), ('maybe', 'Maybe')], default='going', max_length=10)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rsvps', to='events.pokerevent')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_rsvps', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('guest_name', ''), ('user__isnull', False)), models.Q(('guest_name__gt', ''), ('user__isnull', True)), _connector='OR'), name='rsvp_user_or_guest'), models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('user', 'event'), name='unique_user_rsvp'), models.UniqueConstraint(condition=models.Q(('guest_email__gt', '')), fields=('guest_email', 'event'), name='unique_guest_rsvp')],
            },
        ),
    ]
