# Generated by Django 5.2.9 on 2026-01-27 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_started_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='ended_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Ended At'),
        ),
    ]
