# Generated by Django 5.2.9 on 2025-12-20 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_pokerevent_end_date_pokereventrsvp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pokereventattendee',
            name='points_earned',
        ),
        migrations.RemoveField(
            model_name='pokereventattendee',
            name='times_eliminated',
        ),
    ]
