# Generated by Django 5.2.9 on 2025-12-21 03:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='final_position',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Final Position'),
        ),
        migrations.CreateModel(
            name='GuestParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('name', models.CharField(max_length=100, verbose_name='Guest Name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Guest Email')),
                ('final_position', models.PositiveIntegerField(blank=True, null=True, verbose_name='Final Position')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guests', to='events.event', verbose_name='Event')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
