# Generated by Django 5.2.9 on 2025-12-20 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_remove_pokereventattendee_points_earned_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokerevent',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='End Date'),
        ),
        migrations.AlterField(
            model_name='pokerevent',
            name='start_date',
            field=models.DateTimeField(verbose_name='Start Date'),
        ),
    ]
