# Generated by Django 5.2.9 on 2026-01-30 20:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_ended_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='rsvp_enabled',
            field=models.BooleanField(default=True, verbose_name='Allow RSVPs'),
        ),
        migrations.AddField(
            model_name='event',
            name='rsvp_start_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='RSVP Start Date'),
        ),
        migrations.AlterField(
            model_name='event',
            name='end_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='End Date'),
            preserve_default=False,
        ),
    ]
