# Generated by Django 5.2.9 on 2025-12-21 22:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_memberstatistics_and_more'),
        ('events', '0003_alter_participant_final_position_guestparticipant'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'permissions': [('manage_event', 'Can manage event')]},
        ),
        migrations.AlterField(
            model_name='event',
            name='season',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='common.season', verbose_name='Season'),
        ),
    ]
