# Generated by Django 5.2.9 on 2025-12-22 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_alter_event_options_alter_event_season'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventrsvp',
            name='arrival_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Arrival Time'),
        ),
        migrations.AlterField(
            model_name='eventrsvp',
            name='status',
            field=models.CharField(choices=[('arrived', 'Arrived'), ('going', 'Going'), ('late', 'Late'), ('maybe', 'Maybe')], default='going', max_length=10),
        ),
    ]
