# Generated by Django 5.2.9 on 2025-12-22 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_eventrsvp_arrival_time_alter_eventrsvp_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventrsvp',
            options={'verbose_name': 'Event RSVP', 'verbose_name_plural': 'Event RSVPs'},
        ),
    ]
