# Generated by Django 5.2.9 on 2025-12-22 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_alter_eventrsvp_options'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='eventrsvp',
            name='rsvp_user_or_guest',
        ),
        migrations.RemoveConstraint(
            model_name='eventrsvp',
            name='unique_guest_rsvp',
        ),
        migrations.RemoveField(
            model_name='eventrsvp',
            name='guest_email',
        ),
        migrations.RemoveField(
            model_name='eventrsvp',
            name='guest_name',
        ),
        migrations.AddField(
            model_name='event',
            name='scoring_strategy',
            field=models.CharField(blank=True, default='buy_in_distribution', max_length=50),
        ),
        migrations.AddField(
            model_name='participant',
            name='eliminations',
            field=models.PositiveIntegerField(default=0, verbose_name='Eliminations'),
        ),
    ]
