# Generated by Django 5.2.9 on 2025-12-20 21:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_host_candidate',
            field=models.BooleanField(default=False, verbose_name='Is Host Candidate'),
        ),
        migrations.CreateModel(
            name='SeasonProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('season_name', models.CharField(max_length=255, verbose_name='Season Name')),
                ('points', models.IntegerField(default=0, verbose_name='Points')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='season_profiles', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'unique_together': {('user', 'season_name')},
            },
        ),
    ]
